"use client";

import React, { useCallback, useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import {
  ArrowLeft,
  CheckCircle2,
  Loader2,
  Radar,
  Search,
  Sparkles,
  XCircle,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { toast } from "@/components/ui/sonner";
import {
  CORE_DEFAULTS,
  CORE_QUESTIONS,
  missingRequired,
  type AnswerValue,
  type SourcingAnswers,
  type SourcingQuestion,
} from "@/lib/sourcing/questions";

type Step = "brief" | "form" | "progress";

interface RunView {
  id: string;
  roleTitle: string;
  status: "running" | "importing" | "scoring" | "completed" | "failed";
  apifyStatus?: string;
  error?: string;
  stats: { scraped?: number; invalid?: number; duplicates?: number; irrelevant?: number; overLimit?: number; imported?: number };
  scored: number;
  pending: number;
}

const INPUT_CLASS = "border-border bg-background text-foreground placeholder:text-muted-foreground focus-visible:ring-1 focus-visible:ring-ring";
const SELECT_CLASS =
  "h-9 w-full rounded-none border border-border bg-background px-3 text-base text-foreground transition-colors focus-visible:ring-1 focus-visible:ring-ring focus-visible:outline-none cursor-pointer disabled:opacity-50";
const RUN_STORAGE_KEY = "talentrank:sourcing-run";
const POLL_MS = 4000;

const SECTION_COPY: Record<SourcingQuestion["section"], { title: string; hint: string }> = {
  company: { title: "Company & budget", hint: "Context for scoring. LinkedIn can't filter on these." },
  search: { title: "LinkedIn search filters", hint: "Applied to the LinkedIn search and to filtering the results." },
  role: { title: "About this role", hint: "Generated by AI from your description." },
};

function readStoredRun(): string | null {
  try {
    return window.localStorage.getItem(RUN_STORAGE_KEY);
  } catch {
    return null;
  }
}

function storeRun(id: string | null): void {
  try {
    if (id) window.localStorage.setItem(RUN_STORAGE_KEY, id);
    else window.localStorage.removeItem(RUN_STORAGE_KEY);
  } catch {
    // Progress just won't survive a reload
  }
}

function QuestionField({
  question,
  value,
  onChange,
  disabled,
}: {
  question: SourcingQuestion;
  value: AnswerValue | undefined;
  onChange: (value: AnswerValue) => void;
  disabled: boolean;
}): React.JSX.Element {
  const id = `q-${question.id}`;
  const label = (
    <>
      {question.label}
      {question.required && <span className="text-destructive"> *</span>}
    </>
  );
  const help = question.helpText && <p className="text-[13px] leading-relaxed text-muted-foreground">{question.helpText}</p>;

  if (question.type === "multiselect" || question.type === "boolean") {
    const options = question.type === "boolean" ? ["Yes", "No"] : (question.options ?? []);
    const selected =
      question.type === "boolean"
        ? value === undefined
          ? []
          : [value === true ? "Yes" : "No"]
        : Array.isArray(value)
          ? value
          : [];
    return (
      <fieldset className="space-y-2 sm:col-span-2">
        <legend className="mb-2 text-sm font-medium text-foreground">{label}</legend>
        <div className="flex flex-wrap gap-1.5">
          {options.map((opt) => {
            const isOn = selected.includes(opt);
            return (
              <button
                key={opt}
                type="button"
                aria-pressed={isOn}
                disabled={disabled}
                onClick={() => {
                  if (question.type === "boolean") onChange(opt === "Yes");
                  else onChange(isOn ? selected.filter((s) => s !== opt) : [...selected, opt]);
                }}
                className={`rounded-none border px-3 py-1 text-sm font-medium transition-colors cursor-pointer focus-visible:ring-1 focus-visible:ring-ring focus-visible:outline-none disabled:opacity-50 ${
                  isOn
                    ? "border-primary/40 bg-primary/15 text-primary"
                    : "border-border bg-secondary/40 text-muted-foreground hover:border-foreground/30 hover:text-foreground"
                }`}
              >
                {opt}
              </button>
            );
          })}
        </div>
        {help}
      </fieldset>
    );
  }

  const text = typeof value === "string" ? value : "";
  const wide = question.type === "textarea" || (question.type === "text" && question.section !== "company");

  return (
    <div className={`space-y-1.5 ${wide ? "sm:col-span-2" : ""}`}>
      <label htmlFor={id} className="text-sm font-medium text-foreground">
        {label}
      </label>
      {question.type === "select" ? (
        <select
          id={id}
          value={text}
          disabled={disabled}
          onChange={(e) => onChange(e.target.value)}
          className={SELECT_CLASS}
        >
          <option value="">Select…</option>
          {(question.options ?? []).map((opt) => (
            <option key={opt} value={opt}>
              {opt}
            </option>
          ))}
        </select>
      ) : question.type === "textarea" ? (
        <Textarea
          id={id}
          rows={2}
          value={text}
          disabled={disabled}
          placeholder={question.placeholder}
          onChange={(e) => onChange(e.target.value)}
          className={`min-h-[64px] resize-y text-base leading-relaxed ${INPUT_CLASS}`}
        />
      ) : (
        <Input
          id={id}
          type={question.type === "number" ? "number" : "text"}
          inputMode={question.type === "number" ? "numeric" : undefined}
          min={question.type === "number" ? 0 : undefined}
          value={text}
          disabled={disabled}
          placeholder={question.placeholder}
          onChange={(e) => onChange(e.target.value)}
          className={`h-9 text-base ${INPUT_CLASS}`}
        />
      )}
      {help}
    </div>
  );
}

function Stat({ label, value }: { label: string; value: number | undefined }): React.JSX.Element {
  return (
    <div className="rounded-lg border border-border bg-secondary/30 px-3 py-2.5">
      <dt className="text-[13px] text-muted-foreground">{label}</dt>
      <dd className="mt-0.5 font-figure text-xl text-foreground tabular-nums">{value ?? 0}</dd>
    </div>
  );
}

export function SourceCandidatesModal(): React.JSX.Element {
  const router = useRouter();
  const [open, setOpen] = useState(false);
  const [step, setStep] = useState<Step>("brief");
  const [brief, setBrief] = useState("");
  const [roleTitle, setRoleTitle] = useState("");
  const [roleQuestions, setRoleQuestions] = useState<SourcingQuestion[]>([]);
  const [answers, setAnswers] = useState<SourcingAnswers>(CORE_DEFAULTS);
  const [isGenerating, setIsGenerating] = useState(false);
  const [isStarting, setIsStarting] = useState(false);
  const [runId, setRunId] = useState<string | null>(null);
  const [run, setRun] = useState<RunView | null>(null);
  const lastScored = useRef(-1);

  // Resume a search that was still running when the page was closed
  useEffect(() => {
    const stored = readStoredRun();
    if (stored) {
      setRunId(stored);
      setStep("progress");
    }
  }, []);

  const poll = useCallback(async (id: string): Promise<boolean> => {
    try {
      const res = await fetch(`/api/sourcing?id=${encodeURIComponent(id)}`, { cache: "no-store" });
      const data = await res.json().catch(() => null);
      if (res.status === 404 || res.status === 401) {
        storeRun(null);
        setRunId(null);
        return true;
      }
      if (!res.ok || !data) return false; // transient: keep polling

      const view = data as RunView;
      setRun(view);
      // Show newly scored candidates on the dashboard as they land
      if (view.scored !== lastScored.current) {
        lastScored.current = view.scored;
        if (view.scored > 0 || view.status === "completed") router.refresh();
      }
      if (view.status === "completed" || view.status === "failed") {
        storeRun(null);
        if (view.status === "completed") toast.success(`Sourcing done: ${view.stats.imported ?? 0} candidates added.`);
        return true;
      }
    } catch {
      // Network blip: try again on the next tick
    }
    return false;
  }, [router]);

  useEffect(() => {
    if (!runId) return;
    let cancelled = false;
    let timer: ReturnType<typeof setTimeout> | undefined;
    const tick = async () => {
      const done = await poll(runId);
      if (!cancelled && !done) timer = setTimeout(tick, POLL_MS);
    };
    void tick();
    return () => {
      cancelled = true;
      if (timer) clearTimeout(timer);
    };
  }, [runId, poll]);

  const setAnswer = (id: string, value: AnswerValue) => setAnswers((prev) => ({ ...prev, [id]: value }));

  const handleGenerate = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsGenerating(true);
    try {
      const res = await fetch("/api/sourcing", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ action: "questions", brief }),
      });
      const data = await res.json().catch(() => null);
      if (!res.ok) throw new Error(data?.error || "Couldn't generate questions.");
      setRoleTitle(data.roleTitle);
      setRoleQuestions(data.questions);
      // Keep core answers, drop answers to the previous set of AI questions
      setAnswers((prev) => Object.fromEntries(Object.entries(prev).filter(([k]) => !k.startsWith("ai_"))));
      setStep("form");
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Couldn't generate questions.");
    } finally {
      setIsGenerating(false);
    }
  };

  const allQuestions = [...CORE_QUESTIONS, ...roleQuestions];
  const missing = missingRequired(allQuestions, answers);

  const handleStart = async (e: React.FormEvent) => {
    e.preventDefault();
    if (missing.length) {
      toast.error(`Please answer: ${missing.join("; ")}`);
      return;
    }
    setIsStarting(true);
    try {
      const res = await fetch("/api/sourcing", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ action: "start", brief, roleTitle, roleQuestions, answers }),
      });
      const data = await res.json().catch(() => null);
      if (!res.ok) throw new Error(data?.error || "Couldn't start the search.");
      lastScored.current = -1;
      setRun(null);
      storeRun(data.runId);
      setRunId(data.runId);
      setStep("progress");
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Couldn't start the search.");
    } finally {
      setIsStarting(false);
    }
  };

  const startOver = () => {
    storeRun(null);
    setRunId(null);
    setRun(null);
    setStep(roleQuestions.length ? "form" : "brief");
  };

  const busy = isGenerating || isStarting;
  const inFlight = Boolean(runId) && run?.status !== "completed" && run?.status !== "failed";
  const total = (run?.scored ?? 0) + (run?.pending ?? 0);

  return (
    <>
      <Button
        onClick={() => setOpen(true)}
        variant="outline"
        className="group h-9 cursor-pointer gap-2 rounded-none border border-border bg-card px-4 text-sm font-sans font-medium text-foreground shadow-xs transition-all hover:bg-secondary hover:border-foreground"
      >
        {inFlight ? (
          <Loader2 className="h-3.5 w-3.5 animate-spin text-primary motion-reduce:animate-none" aria-hidden="true" />
        ) : (
          <Radar className="h-3.5 w-3.5 text-primary transition-transform group-hover:scale-110" aria-hidden="true" />
        )}
        <span>{inFlight ? "Sourcing…" : "Source with AI"}</span>
      </Button>

      <Dialog open={open} onOpenChange={setOpen}>
        <DialogContent className="max-h-[88vh] flex flex-col p-0 overflow-hidden rounded-xl border border-border bg-card text-foreground shadow-2xl sm:max-w-[760px]">
          <DialogHeader className="p-6 pb-4 border-b border-border shrink-0 space-y-1.5 text-left">
            <DialogTitle className="font-sans text-2xl font-bold tracking-tight text-foreground">
              {step === "progress" ? run?.roleTitle || "Sourcing candidates" : "Source candidates with AI"}
            </DialogTitle>
            <DialogDescription className="text-base leading-relaxed text-muted-foreground">
              {step === "brief" &&
                "Describe who you need. AI turns it into an intake questionnaire, searches LinkedIn, and scores every match against your answers."}
              {step === "form" &&
                "The more you answer, the better the search and the scoring. Required questions are marked *."}
              {step === "progress" &&
                "You can close this window. The search keeps running and candidates appear on the dashboard as they're scored."}
            </DialogDescription>
          </DialogHeader>

          <div className="flex-1 overflow-y-auto p-6">
            {step === "brief" && (
              <form id="sourcing-brief" onSubmit={handleGenerate} className="space-y-1.5">
                <label htmlFor="sourcing-brief-text" className="text-sm font-medium text-foreground">
                  Who are you hiring? <span className="text-destructive">*</span>
                </label>
                <Textarea
                  id="sourcing-brief-text"
                  rows={6}
                  value={brief}
                  disabled={busy}
                  onChange={(e) => setBrief(e.target.value)}
                  placeholder="e.g. A senior React / Next.js engineer for our 30-person fintech startup in Lahore. They'll own the merchant dashboard, work closely with design, and mentor two juniors. Payments or banking experience is a big plus."
                  className={`min-h-[140px] resize-y text-base leading-relaxed ${INPUT_CLASS}`}
                />
                <p className="text-[13px] text-muted-foreground">
                  Mention the stack, seniority, team, product and anything unusual. You&apos;ll answer follow-up questions next.
                </p>
              </form>
            )}

            {step === "form" && (
              <form id="sourcing-form" onSubmit={handleStart} className="space-y-7">
                <div className="space-y-1.5">
                  <label htmlFor="sourcing-role-title" className="text-sm font-medium text-foreground">
                    Role title <span className="text-destructive">*</span>
                  </label>
                  <Input
                    id="sourcing-role-title"
                    value={roleTitle}
                    disabled={busy}
                    onChange={(e) => setRoleTitle(e.target.value)}
                    className={`h-9 text-base ${INPUT_CLASS}`}
                  />
                </div>

                {(["company", "search", "role"] as const).map((section) => {
                  const questions = allQuestions.filter((q) => q.section === section);
                  if (questions.length === 0) return null;
                  return (
                    <section key={section} aria-labelledby={`sourcing-${section}`} className="space-y-4">
                      <div className="border-b border-border pb-2">
                        <h3 id={`sourcing-${section}`} className="flex items-center gap-1.5 text-base font-semibold text-foreground font-sans">
                          {section === "role" && <Sparkles className="h-3.5 w-3.5 text-amber-500" aria-hidden="true" />}
                          {SECTION_COPY[section].title}
                        </h3>
                        <p className="mt-0.5 text-[13px] text-muted-foreground">{SECTION_COPY[section].hint}</p>
                      </div>
                      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
                        {questions.map((q) => (
                          <QuestionField
                            key={q.id}
                            question={q}
                            value={answers[q.id]}
                            onChange={(v) => setAnswer(q.id, v)}
                            disabled={busy}
                          />
                        ))}
                      </div>
                    </section>
                  );
                })}

                <p className="rounded-lg border border-primary/20 bg-primary/5 px-3.5 py-2.5 text-[13px] leading-relaxed text-foreground">
                  Starting runs a paid LinkedIn search through Apify (capped per search, with a daily limit).
                  Profiles already in your pipeline are skipped.
                </p>
              </form>
            )}

            {step === "progress" && (
              <div className="space-y-5" aria-live="polite">
                {!run || run.status === "running" || run.status === "importing" ? (
                  <div className="flex items-start gap-3 rounded-lg border border-border bg-secondary/30 p-4">
                    <Loader2 className="mt-0.5 h-5 w-5 shrink-0 animate-spin text-primary motion-reduce:animate-none" aria-hidden="true" />
                    <div>
                      <p className="text-base font-medium text-foreground">
                        {run?.status === "importing" ? "Filtering and importing profiles…" : "Searching LinkedIn…"}
                      </p>
                      <p className="mt-1 text-sm text-muted-foreground">
                        This usually takes 1 to 3 minutes{run?.apifyStatus ? ` (Apify: ${run.apifyStatus.toLowerCase()})` : ""}.
                      </p>
                    </div>
                  </div>
                ) : run.status === "failed" ? (
                  <div className="flex items-start gap-3 rounded-lg border border-destructive/30 bg-destructive/10 p-4">
                    <XCircle className="mt-0.5 h-5 w-5 shrink-0 text-destructive" aria-hidden="true" />
                    <div>
                      <p className="text-base font-medium text-foreground">The search didn&apos;t return candidates</p>
                      <p className="mt-1 text-sm leading-relaxed text-muted-foreground">{run.error}</p>
                    </div>
                  </div>
                ) : (
                  <div className="space-y-3 rounded-lg border border-border bg-secondary/30 p-4">
                    <div className="flex items-center gap-2">
                      {run.status === "completed" ? (
                        <CheckCircle2 className="h-5 w-5 text-success" aria-hidden="true" />
                      ) : (
                        <Loader2 className="h-5 w-5 animate-spin text-amber-500 motion-reduce:animate-none" aria-hidden="true" />
                      )}
                      <p className="text-base font-medium text-foreground">
                        {run.status === "completed"
                          ? `All ${total} candidates scored`
                          : `Scoring candidates against your answers: ${run.scored} of ${total}`}
                      </p>
                    </div>
                    <div className="h-1.5 overflow-hidden rounded-full bg-secondary" aria-hidden="true">
                      <div
                        className="h-full rounded-full bg-success transition-[width] duration-500"
                        style={{ width: `${total ? Math.round((run.scored / total) * 100) : 0}%` }}
                      />
                    </div>
                  </div>
                )}

                {run && run.stats.scraped ? (
                  <dl className="grid grid-cols-2 gap-2 sm:grid-cols-5">
                    <Stat label="Found on LinkedIn" value={run.stats.scraped} />
                    <Stat label="Already in pipeline" value={run.stats.duplicates} />
                    <Stat label="Missing must-haves" value={run.stats.irrelevant} />
                    <Stat label="Ranked out" value={(run.stats.overLimit ?? 0) + (run.stats.invalid ?? 0)} />
                    <Stat label="Added" value={run.stats.imported} />
                  </dl>
                ) : null}
              </div>
            )}
          </div>

          <DialogFooter className="p-4 border-t border-border shrink-0 bg-secondary/15 flex items-center justify-between gap-2 sm:justify-between">
            <div>
              {step === "form" && (
                <Button
                  type="button"
                  variant="ghost"
                  onClick={() => setStep("brief")}
                  disabled={busy}
                  className="cursor-pointer gap-1.5 text-sm text-muted-foreground hover:text-foreground"
                >
                  <ArrowLeft className="h-3.5 w-3.5" aria-hidden="true" />
                  Edit description
                </Button>
              )}
              {step === "progress" && run && (run.status === "failed" || run.status === "completed") && (
                <Button
                  type="button"
                  variant="ghost"
                  onClick={startOver}
                  disabled={busy}
                  className="cursor-pointer gap-1.5 text-sm text-muted-foreground hover:text-foreground"
                >
                  <ArrowLeft className="h-3.5 w-3.5" aria-hidden="true" />
                  {run.status === "failed" ? "Adjust answers" : "New search"}
                </Button>
              )}
            </div>
            <div className="flex items-center gap-2">
              <Button
                type="button"
                variant="ghost"
                onClick={() => setOpen(false)}
                className="cursor-pointer text-sm text-muted-foreground hover:text-foreground"
              >
                Close
              </Button>
              {step === "brief" && (
                <Button
                  type="submit"
                  form="sourcing-brief"
                  disabled={busy || brief.trim().length < 15}
                  className="cursor-pointer gap-2 rounded-none bg-foreground text-background hover:bg-foreground/85 font-medium text-sm"
                >
                  {isGenerating ? (
                    <Loader2 className="h-4 w-4 animate-spin motion-reduce:animate-none" aria-hidden="true" />
                  ) : (
                    <Sparkles className="h-4 w-4" aria-hidden="true" />
                  )}
                  {isGenerating ? "Writing questions…" : "Generate questions"}
                </Button>
              )}
              {step === "form" && (
                <Button
                  type="submit"
                  form="sourcing-form"
                  disabled={busy || !roleTitle.trim()}
                  className="cursor-pointer gap-2 rounded-none bg-foreground text-background hover:bg-foreground/85 font-medium text-sm"
                >
                  {isStarting ? (
                    <Loader2 className="h-4 w-4 animate-spin motion-reduce:animate-none" aria-hidden="true" />
                  ) : (
                    <Search className="h-4 w-4" aria-hidden="true" />
                  )}
                  {isStarting ? "Starting search…" : "Search LinkedIn"}
                </Button>
              )}
            </div>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </>
  );
}
